name: Compilation test

on:
  push:
    branches: [ "main", "epoll" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test compilation
      run: make webserv
